
// Sample data
INSERT INTO exercises (id, name, description, category, difficulty_level, muscle_group) VALUES
(1, 'Push-ups', 'A bodyweight exercise performed in a prone position by lowering and raising the body using the arms.', 'Strength', 2, 'Chest, Triceps, Core'),
(2, 'Squats', 'A compound movement where you lower your body by bending your knees while keeping your back straight.', 'Strength', 3, 'Legs, Glutes'),
(3, 'Jump Rope', 'A cardiovascular exercise performed by jumping over a swinging rope.', 'Cardio', 2, 'Full Body'),
(4, 'Plank', 'A core exercise where you hold a push-up position with your forearms on the ground.', 'Core Stability', 2, 'Core, Shoulders'),
(5, 'Burpees', 'A full-body explosive movement that involves a squat, jump, and push-up.', 'Cardio', 4, 'Full Body'),
(6, 'Pull-ups', 'An upper-body exercise where you lift your body using a bar.', 'Strength', 4, 'Back, Biceps'),
(7, 'Lunges', 'A lower-body exercise where you step forward and lower your body into a lunge position.', 'Strength', 3, 'Legs, Glutes'),
(8, 'Mountain Climbers', 'A cardio and core exercise where you run in place in a push-up position.', 'Cardio', 3, 'Core, Legs, Shoulders'),
(9, 'Deadlifts', 'A compound movement where you lift a weight from the ground to standing.', 'Strength', 5, 'Back, Hamstrings, Glutes'),
(10, 'Yoga Stretch', 'A series of flexibility exercises to improve range of motion.', 'Flexibility', 1, 'Full Body'),
(11, 'Russian Twists', 'A core exercise where you twist your torso while seated.', 'Core Stability', 3, 'Obliques, Core'),
(12, 'Bench Press', 'A strength exercise performed on a bench where you push weights away from your chest.', 'Strength', 4, 'Chest, Triceps, Shoulders'),
(13, 'Jump Squats', 'A plyometric movement that combines squats with explosive jumps.', 'Cardio', 3, 'Legs, Glutes'),
(14, 'Bicycle Crunches', 'A core exercise where you alternate touching elbows to opposite knees.', 'Core Stability', 3, 'Abs, Obliques'),
(15, 'Kettlebell Swings', 'A dynamic movement that involves swinging a kettlebell using the hips.', 'Strength', 4, 'Glutes, Hamstrings, Core'),
(16, 'Plank to Push-up', 'A core and upper-body exercise transitioning from plank to push-up position.', 'Strength', 3, 'Core, Shoulders, Arms'),
(17, 'Jumping Jacks', 'A full-body cardio exercise where you jump while moving arms and legs outward.', 'Cardio', 1, 'Full Body'),
(18, 'Side Lunges', 'A lower-body exercise where you lunge sideways to work different leg muscles.', 'Strength', 3, 'Legs, Glutes, Inner Thighs'),
(19, 'Box Jumps', 'A plyometric exercise where you jump onto a box or elevated surface.', 'Cardio', 4, 'Legs, Glutes'),
(20, 'Hamstring Curls', 'A leg exercise using a machine to curl weights with the hamstrings.', 'Strength', 3, 'Hamstrings'),
(21, 'Lat Pulldown', 'A back-strengthening exercise using a machine with a bar to pull down.', 'Strength', 3, 'Back, Biceps'),
(22, 'Seated Shoulder Press', 'A weightlifting exercise where you press weights overhead.', 'Strength', 4, 'Shoulders, Triceps'),
(23, 'Toe Touches', 'A flexibility exercise where you reach forward to touch your toes.', 'Flexibility', 1, 'Hamstrings, Lower Back'),
(24, 'Hanging Leg Raises', 'A core exercise where you lift your legs while hanging from a bar.', 'Core Stability', 4, 'Lower Abs, Hip Flexors');